PropertyRentalManagement/Models/Appartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PropertyRentalManagement.Models;

public partial class Appartment
{
    public int ApartmentId { get; set; }

    public int StatusId { get; set; }

    public int OwnerId { get; set; }

    public int AptNumber { get; set; }

    public int AptSize { get; set; }

    public decimal AptRent { get; set; }

    public int AptNumberOfRooms { get; set; }

    public string AptDescription { get; set; } = null!;

    public int BuildingId { get; set; }

    public int ManagerId { get; set; }

    public virtual Building Building { get; set; } = null!;

    public virtual User Manager { get; set; } = null!;

    public virtual User Owner { get; set; } = null!;

    public virtual Status Status { get; set; } = null!;

}

PropertyRentalManagement/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PropertyRentalManagement.Models;

namespace PropertyRentalManagement.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly FinalProjectDbContext _context;
        bool didSend;

        public AppointmentsController(FinalProjectDbContext context)
        {
            _context = context;
        }

        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            var finalProjectDbContext = _context.Appointments.Include(a => a.Manager).Include(a => a.Status).Include(a => a.Tenant);
            return View(await finalProjectDbContext.ToListAsync());
        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Manager)
                .Include(a => a.Status)
                .Include(a => a.Tenant)
                .FirstOrDefaultAsync(m => m.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // GET: Appointments/Create
        public IActionResult Create()
        {
            int userType = Convert.ToInt32(Request.Cookies["UserType"]);

            if (userType == 2)
            {              
                ViewData["TenantId"] = new SelectList(_context.Users.Where(m => m.UserType == 3), "UserId", "Name");
            }
            else if (userType == 3)
            {
                ViewData["TenantId"] = new SelectList(_context.Users.Where(m => m.UserType == 2), "UserId", "Name");
            }

            if (didSend == true)
            {
                ViewData["Message"] = "Appointment Scheduled!";
            }
            else
            {
                ViewData["Message"] = "";
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AppointmentId,TenantId,ManagerId,AppointmentDate,Location")] Appointment appointment)
        {

            int userId = Convert.ToInt32(Request.Cookies["UserId"]);
            int userType = Convert.ToInt32(Request.Cookies["UserType"]);

            if (userType == 2)
            {
                appointment.ManagerId = userId;
                ViewData["TenantId"] = new SelectList(_context.Users.Where(m => m.UserType == 3), "UserId", "Name", appointment.ManagerId);
            }
            else if (userType == 3)
            {
                appointment.TenantId = userId;
                ViewData["TenantId"] = new SelectList(_context.Users.Where(m => m.UserType == 2), "UserId", "Name", appointment.TenantId);
            }

            if (appointment.AppDateTime != null)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                didSend = true;
                return RedirectToAction(nameof(Index));
            }

            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            ViewData["ManagerId"] = new SelectList(_context.Users, "UserId", "UserId", appointment.ManagerId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "StatusId", appointment.StatusId);
            ViewData["TenantId"] = new SelectList(_context.Users, "UserId", "UserId", appointment.TenantId);
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AppointmentId,ManagerId,TenantId,AppDateTime,StatusId")] Appointment appointment)
        {
            if (id != appointment.AppointmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.AppointmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManagerId"] = new SelectList(_context.Users, "UserId", "UserId", appointment.ManagerId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "StatusId", appointment.StatusId);
            ViewData["TenantId"] = new SelectList(_context.Users, "UserId", "UserId", appointment.TenantId);
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Manager)
                .Include(a => a.Status)
                .Include(a => a.Tenant)
                .FirstOrDefaultAsync(m => m.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment != null)
            {
                _context.Appointments.Remove(appointment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
            return _context.Appointments.Any(e => e.AppointmentId == id);
        }
    }
}

PropertyRentalManagement/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PropertyRentalManagement.Models;

namespace PropertyRentalManagement.Controllers
{
    public class MessagesController : Controller
    {
        private readonly FinalProjectDbContext _context;

        bool didSend = false;

        public MessagesController(FinalProjectDbContext context)
        {
            _context = context;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            var finalProjectDbContext = _context.Messages.Where(m => m.ReceiverId == Convert.ToInt32(Request.Cookies["UserId"]));
            return View(await finalProjectDbContext.ToListAsync());
            
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.MessageId == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            int userType = Convert.ToInt32(Request.Cookies["UserType"]);

            if (userType == 2)
            {
                ViewData["TenantId"] = new SelectList(_context.Users.Where(m => m.UserType == 3), "UserId", "Name");
            }
            else if (userType == 3)
            {
                ViewData["TenantId"] = new SelectList(_context.Users.Where(m => m.UserType == 2), "UserId", "Name");
            }

            if (didSend == true)
            {
                ViewData["Message"] = "Message Sent!";
            }
            else
            {
                ViewData["Message"] = "";
            }
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MessageId,SenderId,ReceiverId,Content,DateTime")] Message message)
        {
            int userId = Convert.ToInt32(Request.Cookies["UserId"]);
            int userType = Convert.ToInt32(Request.Cookies["UserType"]);

            if (userType == 2)
            {
                message.SenderId = userId;
                ViewData["TenantId"] = new SelectList(_context.Users.Where(m => m.UserType == 3), "UserId", "Name", message.SenderId);
            }
            else if (userType == 3)
            {
                message.SenderId = userId;
                ViewData["TenantId"] = new SelectList(_context.Users.Where(m => m.UserType == 2), "UserId", "Name", message.SenderId);
            }
            if (ModelState.IsValid)
            {
                message.DateTime = DateTime.Now;
                _context.Add(message);
                didSend = true;
                await _context.SaveChangesAsync();
            }
            return Create();
        }

        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages.FindAsync(id);
            if (message == null)
            {
                return NotFound();
            }
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MessageId,SenderId,ReceiverId,Content,DateTime")] Message message)
        {
            if (id != message.MessageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(message);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessageExists(message.MessageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.MessageId == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var message = await _context.Messages.FindAsync(id);
            if (message != null)
            {
                _context.Messages.Remove(message);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MessageExists(int id)
        {
            return _context.Messages.Any(e => e.MessageId == id);
        }
    }
}

PropertyRentalManagement/Views/Appartments/Create.cshtml
@model PropertyRentalManagement.Models.Appartment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Appartment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ApartmentId" class="control-label"></label>
                <input asp-for="ApartmentId" class="form-control" />
                <span asp-validation-for="ApartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class ="form-control" asp-items="ViewBag.StatusId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class ="form-control" asp-items="ViewBag.OwnerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AptNumber" class="control-label"></label>
                <input asp-for="AptNumber" class="form-control" />
                <span asp-validation-for="AptNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptSize" class="control-label"></label>
                <input asp-for="AptSize" class="form-control" />
                <span asp-validation-for="AptSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptRent" class="control-label"></label>
                <input asp-for="AptRent" class="form-control" />
                <span asp-validation-for="AptRent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptNumberOfRooms" class="control-label"></label>
                <input asp-for="AptNumberOfRooms" class="form-control" />
                <span asp-validation-for="AptNumberOfRooms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptDescription" class="control-label"></label>
                <input asp-for="AptDescription" class="form-control" />
                <span asp-validation-for="AptDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BuildingId" class="control-label"></label>
                <select asp-for="BuildingId" class ="form-control" asp-items="ViewBag.BuildingId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ManagerId" class="control-label"></label>
                <select asp-for="ManagerId" class ="form-control" asp-items="ViewBag.ManagerId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyRentalManagement/Views/Appartments/Delete.cshtml
@model PropertyRentalManagement.Models.Appartment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appartment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptRent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptRent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptNumberOfRooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptNumberOfRooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Building)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Building.BuildingId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manager.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.StatusId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ApartmentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PropertyRentalManagement/Views/Appartments/Details.cshtml
@model PropertyRentalManagement.Models.Appartment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Appartment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptRent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptRent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptNumberOfRooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptNumberOfRooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Building)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Building.BuildingId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manager.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.StatusId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ApartmentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PropertyRentalManagement/Views/Appartments/Edit.cshtml
@model PropertyRentalManagement.Models.Appartment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Appartment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ApartmentId" />
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptNumber" class="control-label"></label>
                <input asp-for="AptNumber" class="form-control" />
                <span asp-validation-for="AptNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptSize" class="control-label"></label>
                <input asp-for="AptSize" class="form-control" />
                <span asp-validation-for="AptSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptRent" class="control-label"></label>
                <input asp-for="AptRent" class="form-control" />
                <span asp-validation-for="AptRent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptNumberOfRooms" class="control-label"></label>
                <input asp-for="AptNumberOfRooms" class="form-control" />
                <span asp-validation-for="AptNumberOfRooms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AptDescription" class="control-label"></label>
                <input asp-for="AptDescription" class="form-control" />
                <span asp-validation-for="AptDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BuildingId" class="control-label"></label>
                <select asp-for="BuildingId" class="form-control" asp-items="ViewBag.BuildingId"></select>
                <span asp-validation-for="BuildingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManagerId" class="control-label"></label>
                <select asp-for="ManagerId" class="form-control" asp-items="ViewBag.ManagerId"></select>
                <span asp-validation-for="ManagerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyRentalManagement/Views/Appartments/Index.cshtml
@model IEnumerable<PropertyRentalManagement.Models.Appartment>

@{
    ViewData["Title"] = "Index";
    var imagePath = "~/Assets/richmond-apartments-for-sale.jpg";
}

<h1>Manage Appartments</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Appartment Preview
            </th>
            <th>
                Apartment Number
            </th>
            <th>
                Size
            </th>
            <th>
                Monthly Rent $
            </th>
            <th>
                Number Of Rooms
            </th>
            <th>
                Description
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Building)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manager)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Owner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    <img src="@Url.Content(imagePath)" alt="Appartment" style="width: 75px; height: 75px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AptNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AptSize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AptRent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AptNumberOfRooms)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AptDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Building.BuildingName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manager.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.StatusDescription)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ApartmentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ApartmentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ApartmentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PropertyRentalManagement/Views/Appartments/TenantView.cshtml
@model IEnumerable<PropertyRentalManagement.Models.Appartment>

@{
    ViewData["Title"] = "TenantView";
    var imagePath = "~/Assets/richmond-apartments-for-sale.jpg";
}

<h1>Welcome To PRM!</h1>

<form method="post">
    <p>
        Max Rent : <input type="number" id="Rent" name="Rent" step=".01" />
        Number of rooms : <input type="number" id="numberOfRooms" name="numberOfRooms" />
        <input type="submit" value="Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Appartment Preview
            </th>
            <th>
                Appartment Number
            </th>
            <th>
                Apartment Size (Meters)
            </th>
            <th>
                Monthly Rent $
            </th>
            <th>
                Number of Rooms
            </th>
            <th>
                Description
            </th>
            <th>
                Building
            </th>
            <th>
                Manager
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                @if (item.StatusId == 1)
                {
                    <tr>
                        <td>
                            <img src="@Url.Content(imagePath)" alt="Appartment" style="width: 100px; height: 100px"/>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AptNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AptSize)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AptRent)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AptNumberOfRooms)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AptDescription)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Building.BuildingName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Manager.Name)
                        </td>
                        <td>
                            @Html.ActionLink("Schedule an appointment", "Create", "Appointments");
                        </td>
                    </tr>
                }
            }
        }
        else
        {
            <td>No data available</td>
        }
    </tbody>
</table>

<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <db class="col-sm-2">
            @Html.ActionLink("Send New Message", "Create", "Messages")
        </db>
        <db class="col-sm-2">
            @Html.ActionLink("Message Inbox", "Index", "Messages")
        </db>
    </dl>
</div>