PropertyRentalManagement/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PropertyRentalManagement.Models;

public partial class User
{
   
    public int UserId { get; set; }
    [Required]
    public string Name { get; set; } = null!;
    [Required(ErrorMessage = "Email is required!")]
    [RegularExpression("^[a-z09_\\+-]+(\\.[a-z0-9_\\+-]+)(\\.[a-z0-9-]+)*\\.([a-z]{2,4})$", ErrorMessage ="Not valid Email!")]
    public string Email { get; set; } = null!;
    [Required(ErrorMessage="Password Required")]
    public string Password { get; set; } = null!;

    public int UserType { get; set; } = 3;

    public virtual ICollection<Appartment> AppartmentManagers { get; set; } = new List<Appartment>();

    public virtual ICollection<Appartment> AppartmentOwners { get; set; } = new List<Appartment>();

    public virtual ICollection<Appointment> AppointmentManagers { get; set; } = new List<Appointment>();

    public virtual ICollection<Appointment> AppointmentTenants { get; set; } = new List<Appointment>();

    public virtual UserType UserTypeNavigation { get; set; } = null!;
}

PropertyRentalManagement/Models/UserType.cs
using System;
using System.Collections.Generic;

namespace PropertyRentalManagement.Models;

public partial class UserType
{
    public int UserTypeId { get; set; }

    public string UserDescription { get; set; } = null!;

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}

PropertyRentalManagement/Controllers/AppartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PropertyRentalManagement.Models;

namespace PropertyRentalManagement.Controllers
{
    public class AppartmentsController : Controller
    {
        private readonly FinalProjectDbContext _context;

        public AppartmentsController(FinalProjectDbContext context)
        {
            _context = context;
        }

        // GET: Appartments
        public async Task<IActionResult> Index()
        {
            var finalProjectDbContext = _context.Appartments.Include(a => a.Building).Include(a => a.Manager).Include(a => a.Owner).Include(a => a.Status);
            return View(await finalProjectDbContext.ToListAsync());
        }

        public async Task<IActionResult> TenantViewAsync()
        {
            var finalProjectDbContext = _context.Appartments.Include(a => a.Building).Include(a => a.Manager).Include(a => a.Owner).Include(a => a.Status);
            return View(await finalProjectDbContext.ToListAsync());

        }

        [HttpPost]
        public async Task<IActionResult> TenantViewAsync(int Rent, int numberOfRooms)
        {
            var finalProjectDbContext = _context.Appartments.Include(a => a.Building).Include(a => a.Manager).Include(a => a.Owner).Include(a => a.Status); ;
            if (Rent > 0)
            {
                finalProjectDbContext = _context.Appartments.Where(s => s.AptRent <= Rent).Include(a => a.Building).Include(a => a.Manager).Include(a => a.Owner).Include(a => a.Status); ;
            }
            if (numberOfRooms > 0)
            {
                finalProjectDbContext = _context.Appartments.Where(s => s.AptNumberOfRooms >= numberOfRooms).Include(a => a.Building).Include(a => a.Manager).Include(a => a.Owner).Include(a => a.Status); ;
            }
            return View(await finalProjectDbContext.ToListAsync());
        }

            // GET: Appartments/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appartment = await _context.Appartments
                .Include(a => a.Building)
                .Include(a => a.Manager)
                .Include(a => a.Owner)
                .Include(a => a.Status)
                .FirstOrDefaultAsync(m => m.ApartmentId == id);
            if (appartment == null)
            {
                return NotFound();
            }

            return View(appartment);
        }

        // GET: Appartments/Create
        public IActionResult Create()
        {
            ViewData["BuildingId"] = new SelectList(_context.Buildings, "BuildingId", "BuildingId");
            ViewData["ManagerId"] = new SelectList(_context.Users, "UserId", "UserId");
            ViewData["OwnerId"] = new SelectList(_context.Users, "UserId", "UserId");
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "StatusId");
            return View();
        }

        // POST: Appartments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ApartmentId,StatusId,OwnerId,AptNumber,AptSize,AptRent,AptNumberOfRooms,AptDescription,BuildingId,ManagerId")] Appartment appartment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appartment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BuildingId"] = new SelectList(_context.Buildings, "BuildingId", "BuildingId", appartment.BuildingId);
            ViewData["ManagerId"] = new SelectList(_context.Users, "UserId", "UserId", appartment.ManagerId);
            ViewData["OwnerId"] = new SelectList(_context.Users, "UserId", "UserId", appartment.OwnerId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "StatusId", appartment.StatusId);
            return View(appartment);
        }

        // GET: Appartments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appartment = await _context.Appartments.FindAsync(id);
            if (appartment == null)
            {
                return NotFound();
            }
            ViewData["BuildingId"] = new SelectList(_context.Buildings, "BuildingId", "BuildingId", appartment.BuildingId);
            ViewData["ManagerId"] = new SelectList(_context.Users, "UserId", "UserId", appartment.ManagerId);
            ViewData["OwnerId"] = new SelectList(_context.Users, "UserId", "UserId", appartment.OwnerId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "StatusId", appartment.StatusId);
            return View(appartment);
        }

        // POST: Appartments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ApartmentId,StatusId,OwnerId,AptNumber,AptSize,AptRent,AptNumberOfRooms,AptDescription,BuildingId,ManagerId")] Appartment appartment)
        {
            if (id != appartment.ApartmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appartment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppartmentExists(appartment.ApartmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BuildingId"] = new SelectList(_context.Buildings, "BuildingId", "BuildingId", appartment.BuildingId);
            ViewData["ManagerId"] = new SelectList(_context.Users, "UserId", "UserId", appartment.ManagerId);
            ViewData["OwnerId"] = new SelectList(_context.Users, "UserId", "UserId", appartment.OwnerId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "StatusId", appartment.StatusId);
            return View(appartment);
        }

        // GET: Appartments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appartment = await _context.Appartments
                .Include(a => a.Building)
                .Include(a => a.Manager)
                .Include(a => a.Owner)
                .Include(a => a.Status)
                .FirstOrDefaultAsync(m => m.ApartmentId == id);
            if (appartment == null)
            {
                return NotFound();
            }

            return View(appartment);
        }

        // POST: Appartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appartment = await _context.Appartments.FindAsync(id);
            if (appartment != null)
            {
                _context.Appartments.Remove(appartment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppartmentExists(int id)
        {
            return _context.Appartments.Any(e => e.ApartmentId == id);
        }
    }
}

PropertyRentalManagement/Controllers/BuildingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PropertyRentalManagement.Models;

namespace PropertyRentalManagement.Controllers
{
    public class BuildingsController : Controller
    {
        private readonly FinalProjectDbContext _context;

        public BuildingsController(FinalProjectDbContext context)
        {
            _context = context;
        }

        // GET: Buildings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Buildings.ToListAsync());
        }

        // GET: Buildings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var building = await _context.Buildings
                .FirstOrDefaultAsync(m => m.BuildingId == id);
            if (building == null)
            {
                return NotFound();
            }

            return View(building);
        }

        // GET: Buildings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Buildings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BuildingId,Address,BuildingName")] Building building)
        {
            if (ModelState.IsValid)
            {
                _context.Add(building);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(building);
        }

        // GET: Buildings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var building = await _context.Buildings.FindAsync(id);
            if (building == null)
            {
                return NotFound();
            }
            return View(building);
        }

        // POST: Buildings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BuildingId,Address,BuildingName")] Building building)
        {
            if (id != building.BuildingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(building);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuildingExists(building.BuildingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(building);
        }

        // GET: Buildings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var building = await _context.Buildings
                .FirstOrDefaultAsync(m => m.BuildingId == id);
            if (building == null)
            {
                return NotFound();
            }

            return View(building);
        }

        // POST: Buildings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var building = await _context.Buildings.FindAsync(id);
            if (building != null)
            {
                _context.Buildings.Remove(building);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BuildingExists(int id)
        {
            return _context.Buildings.Any(e => e.BuildingId == id);
        }
    }
}

PropertyRentalManagement/Views/Users/Create.cshtml
@model PropertyRentalManagement.Models.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserType" class="control-label"></label>
                <select asp-for="UserType" class ="form-control" asp-items="ViewBag.UserType"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyRentalManagement/Views/Users/Delete.cshtml
@model PropertyRentalManagement.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserTypeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserTypeNavigation.UserTypeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PropertyRentalManagement/Views/Users/Details.cshtml
@model PropertyRentalManagement.Models.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserTypeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserTypeNavigation.UserTypeId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.UserId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PropertyRentalManagement/Views/Users/Edit.cshtml
@model PropertyRentalManagement.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserType" class="control-label"></label>
                <select asp-for="UserType" class="form-control" asp-items="ViewBag.UserType"></select>
                <span asp-validation-for="UserType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PropertyRentalManagement/Views/Users/Index.cshtml
@model IEnumerable<PropertyRentalManagement.Models.User>

@{
    ViewData["Title"] = "Index";
    var imagePath = "~/Assets/profile_default_pic.jpg";
}

<h1>User Managment</h1>

<h2>Search - Users</h2>
<form method="post">
    <p>
        Email : <input type="text" id="Email" name="Email" />
        <input type="submit" value="Search" />
    </p>
</form>

<br/>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Profile Picture
            </th>
            <th>
                Name
            </th>
            <th>
              Email
            </th>
            <th>
                User type
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
               <img src="@Url.Content(imagePath)" alt="User" style="width: 100px; height: 100px" />
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserTypeNavigation.UserDescription)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.UserId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.UserId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.UserId">Delete</a>
            </td>
        </tr>
}
    </tbody>
            <td>
                @Html.ActionLink("Manage Buildings", "Index", "Buildings")
            </td>
            <td>
                @Html.ActionLink("Manage Appartments", "Index", "Appartments")
            </td>
</table>